# Generated by Django 5.0.7 on 2024-08-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_remove_game_platform_game_platform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Stock',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='platform',
            new_name='platforms',
        ),
    ]
