# Generated by Django 5.0.7 on 2024-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0005_platform_icon_alter_game_genre_alter_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='platforms_images/'),
        ),
    ]
