# Generated by Django 5.0.7 on 2024-08-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0006_alter_platform_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
